# Generated by Django 5.2.12 on 2026-05-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cleanliness', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('room_comfort', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('food', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('location_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('service_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='search.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
