# Generated by Django 5.2.12 on 2026-05-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='baggage',
            field=models.CharField(blank=True, default='20kg', max_length=50),
        ),
        migrations.AddField(
            model_name='flight',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.CharField(blank=True, default='1h 50m', max_length=50),
        ),
    ]
